// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package postgres

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type User struct {
	ID           uuid.UUID
	DisplayID    string
	Username     string
	Email        string
	PasswordHash string
	Bio          sql.NullString
	IconUrl      sql.NullString
	CreatedAt    time.Time
	UpdatedAt    time.Time
}
