version: "2"

linters:
  enable:
    - errcheck
    - staticcheck
    - unused
    - ineffassign
    - govet
    - gosec
    - misspell
    - unconvert
    - unparam

formatters:
  enable:
    - gofmt
    - goimports
    - gofumpt

run:
  timeout: 5m
